version: '3'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    expose:
      - 9000
    volumes:
      - ./app:/app
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mariadb:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
